Transfer file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,12 +1,29 @@
 #!/usr/bin/env bash
-# uploads a file to a server
+# uploads a file
 
-msg="Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+if [ $# -lt 4]
+then
+	echo "usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+	exit 1
+fi
 
-if [ "$4" ]; then
-   scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~"
-elif [ "$3" ]; then
-     scp -o StrictHostKeyChecking=no "$1" "$3@$2~"
+#Assigning parameters
+
+path_to_file=$1
+ip=$2
+username=$3
+path_to_ssh_key=$4
+
+#disabling strict host key checking
+
+scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+
+
+#checking if the transfer was successful
+
+if [ $? -eq 0]
+then
+	echo "FILE WAS TRANSFERED SUCCESSFULLY"
 else
-	echo "$msg";
+	echo "FILE TRANSFER FAIL"
 fi
